export const products = [
    {
        id: "1",
        name: "Nike Air Jordan 1 Retro High",
        price: 189990,
        salePrice: 169990,
        description: "El Air Jordan 1 Retro High OG recupera el diseño clásico que lo empezó todo. Con una construcción de cuero premium y la icónica amortiguación Air, estas zapatillas ofrecen comodidad y estilo duradero.",
        images: ["/Hero New.png", "/Hombre 1.png", "/Mujer 1.png", "/Nino P1.webp"],
        brand: "Jordan",
        category: "Hombre",
        stock: 12,
        features: [
            "Cuero de alta calidad para durabilidad y soporte",
            "Unidad Air-Sole en el talón para amortiguación ligera",
            "Suela de goma sólida con ranuras flexibles",
            "Logo Wings en el tobillo",
        ],
        sizes: [40, 41, 42, 43, 44, 45],
        colors: ["University Blue", "Chicago", "Shadow"],
    },
    {
        id: "2",
        name: "Adidas Yeezy Boost 350 V2",
        price: 249990,
        salePrice: 229990,
        description: "Diseñadas por Kanye West, las Yeezy Boost 350 V2 son el epítome del estilo urbano contemporáneo. Cuentan con una parte superior de Primeknit reestructurado y la tecnología Boost patentada de Adidas.",
        images: ["/Hombre 1.png", "/Hero New.png", "/Mujer 1.png"],
        brand: "Adidas",
        category: "Hombre",
        stock: 8,
        features: [
            "Parte superior Primeknit adaptable",
            "Tecnología de amortiguación Boost",
            "Diseño tipo calcetín para mayor comodidad",
            "Suela de goma semitranslúcida",
        ],
        sizes: [39, 40, 41, 42, 43],
        colors: ["Onyx", "Bone", "Zebra"],
    },
    {
        id: "3",
        name: "Nike Dunk Low Retro",
        price: 119990,
        description: "Creadas para la cancha pero llevadas a las calles, las Nike Dunk Low Retro vuelven con superposiciones nítidas y colores originales del equipo. Este ícono del baloncesto canaliza el estilo de los 80.",
        images: ["/Mujer 1.png", "/Hero New.png", "/Hombre 1.png"],
        brand: "Nike",
        category: "Mujer",
        stock: 15,
        features: [
            "Parte superior de cuero brillante",
            "Entresuela de espuma para amortiguación reactiva",
            "Cuello acolchado de corte bajo",
            "Suela de goma con punto de giro clásico",
        ],
        sizes: [36, 37, 38, 39, 40],
        colors: ["Panda", "Rose Whisper", "Cacao Wow"],
    },
];
