export const products = [
    {
        id: "1",
        name: "Nike Air Jordan 1 Retro High",
        price: 189990,
        salePrice: 169990,
        description: "El Air Jordan 1 Retro High OG recupera el diseño clásico que lo empezó todo. Con una construcción de cuero premium y la icónica amortiguación Air, estas zapatillas ofrecen comodidad y estilo duradero.",
        images: [
            "https://images.unsplash.com/photo-1556906781-9a412961c28c?w=800&q=80",
            "https://images.unsplash.com/photo-1612902456551-404b5c9e8e14?w=800&q=80",
            "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80"
        ],
        brand: "Jordan",
        category: "Hombre",
        stock: 12,
        features: [
            "Cuero de alta calidad para durabilidad y soporte",
            "Unidad Air-Sole en el talón para amortiguación ligera",
            "Suela de goma sólida con ranuras flexibles",
            "Logo Wings en el tobillo",
        ],
        sizes: [40, 41, 42, 43, 44, 45],
        colors: ["University Blue", "Chicago", "Shadow"],
    },
    {
        id: "2",
        name: "Adidas Yeezy Boost 350 V2",
        price: 249990,
        salePrice: 229990,
        description: "Diseñadas por Kanye West, las Yeezy Boost 350 V2 son el epítome del estilo urbano contemporáneo. Cuentan con una parte superior de Primeknit reestructurado y la tecnología Boost patentada de Adidas.",
        images: [
            "https://images.unsplash.com/photo-1586525198428-225f6f12c240?w=800&q=80",
            "https://images.unsplash.com/photo-1617614838645-0d62eb74aa2b?w=800&q=80",
        ],
        brand: "Adidas",
        category: "Hombre",
        stock: 8,
        features: [
            "Parte superior Primeknit adaptable",
            "Tecnología de amortiguación Boost",
            "Diseño tipo calcetín para mayor comodidad",
            "Suela de goma semitranslúcida",
        ],
        sizes: [39, 40, 41, 42, 43],
        colors: ["Onyx", "Bone", "Zebra"],
    },
    {
        id: "3",
        name: "Nike Dunk Low Retro",
        price: 119990,
        description: "Creadas para la cancha pero llevadas a las calles, las Nike Dunk Low Retro vuelven con superposiciones nítidas y colores originales del equipo. Este ícono del baloncesto canaliza el estilo de los 80.",
        images: [
            "https://images.unsplash.com/photo-1597045566677-8cf032ed6634?w=800&q=80",
            "https://images.unsplash.com/photo-1585854467604-41b2e1a6981e?w=800&q=80",
        ],
        brand: "Nike",
        category: "Mujer",
        stock: 15,
        features: [
            "Parte superior de cuero brillante",
            "Entresuela de espuma para amortiguación reactiva",
            "Cuello acolchado de corte bajo",
            "Suela de goma con punto de giro clásico",
        ],
        sizes: [36, 37, 38, 39, 40],
        colors: ["Panda", "Rose Whisper", "Cacao Wow"],
    },
    {
        id: "4",
        name: "Nike Air Max 90",
        price: 149990,
        description: "El Nike Air Max 90 se mantiene fiel a sus raíces con la icónica suela Waffle, superposiciones cosidas y detalles clásicos de TPU. Los colores frescos le dan un aspecto moderno.",
        images: [
            "https://images.unsplash.com/photo-1605348532760-6753d2c43329?w=800&q=80",
            "https://images.unsplash.com/photo-1579338559194-a162d19bd842?w=800&q=80",
        ],
        brand: "Nike",
        category: "Lifestyle",
        stock: 20,
        features: [
            "Unidad Max Air en el talón para amortiguación",
            "Cuello acolchado de corte bajo",
            "Suela de goma Waffle para tracción",
            "Superposiciones cosidas y detalles de TPU",
        ],
        sizes: [38, 39, 40, 41, 42, 43],
        colors: ["Infrared", "Triple White", "Black"],
    },
    {
        id: "5",
        name: "New Balance 550",
        price: 129990,
        description: "El regreso de una leyenda del baloncesto. El 550 rinde homenaje a los jugadores profesionales de los 90 y a la ropa de calle que definió una generación de baloncesto.",
        images: [
            "https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&q=80",
            "https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?w=800&q=80"
        ],
        brand: "New Balance",
        category: "Lifestyle",
        stock: 10,
        features: [
            "Empeine de cuero, sintético y malla",
            "Suela de goma para tracción y durabilidad",
            "Cierre con cordones ajustable",
            "Diseño inspirado en el baloncesto de los 80",
        ],
        sizes: [40, 41, 42, 43, 44],
        colors: ["White/Green", "White/Grey", "White/Navy"],
    },
    {
        id: "6",
        name: "Adidas Samba OG",
        price: 99990,
        description: "Nacidas en el campo de fútbol, las Samba son un ícono atemporal del estilo urbano. Esta versión se mantiene fiel al legado con una parte superior de cuero suave y superposiciones de gamuza.",
        images: [
            "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&q=80",
            "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&q=80"
        ],
        brand: "Adidas",
        category: "Retro",
        stock: 25,
        features: [
            "Cierre de cordones",
            "Parte superior de cuero granulado con gamuza",
            "Forro de piel sintética",
            "Suela de caucho color caramelo",
        ],
        sizes: [39, 40, 41, 42, 43, 44],
        colors: ["White/Black", "Black/White"],
    },
    {
        id: "7",
        name: "Puma Suede Classic XXI",
        price: 69990,
        description: "El Suede llegó a la escena en 1968 y ha estado cambiando el juego desde entonces. Usado por los íconos de cada generación, se ha mantenido clásico a través de todo.",
        images: [
            "https://images.unsplash.com/photo-1543508282-6319a3e2621f?w=800&q=80",
        ],
        brand: "Puma",
        category: "Lifestyle",
        stock: 18,
        features: [
            "Empeine de gamuza clásica",
            "Cierre completo de cordones",
            "Entresuela y suela de goma",
            "Franja PUMA Formstrip en los lados",
        ],
        sizes: [38, 39, 40, 41, 42],
        colors: ["Black/White", "Red/White", "Navy/White"],
    },
    {
        id: "8",
        name: "Air Jordan 4 Retro",
        price: 199990,
        description: "El Air Jordan 4 Retro ofrece amortiguación ligera y un diseño esculpido actualizado con detalles premium. Mantiene la esencia del modelo original de 1989.",
        images: [
            "https://images.unsplash.com/photo-1575537302964-96cd47c06b1b?w=800&q=80",
        ],
        brand: "Jordan",
        category: "Lifestyle",
        stock: 5,
        features: [
            "Unidades Air-Sole en el talón y el antepié",
            "Parte superior de cuero y malla",
            "Suela de goma con patrón de espiga",
            "Clips de plástico para los cordones",
        ],
        sizes: [41, 42, 43, 44, 45, 46],
        colors: ["Military Black", "Thunder", "Red Cement"],
    },
    {
        id: "9",
        name: "Nike Air Force 1 '07",
        price: 109990,
        salePrice: 99990,
        description: "El fulgor vive en el Nike Air Force 1 '07, el modelo original de baloncesto que introduce un nuevo giro a lo que mejor conoces: cuero impecable y colores perfectos.",
        images: [
            "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80",
        ],
        brand: "Nike",
        category: "Lifestyle",
        stock: 30,
        features: [
            "Amortiguación Nike Air diseñada para el baloncesto",
            "Cuello bajo y acolchado",
            "Suela de goma completa",
            "Perforaciones en la punta",
        ],
        sizes: [36, 37, 38, 39, 40, 41, 42, 43],
        colors: ["White", "Black"],
    },
    {
        id: "10",
        name: "New Balance 2002R",
        price: 139990,
        description: "Inspiradas en el calzado de running de los 2000, las 2002R elevan tu estilo diario. La entresuela ABZORB y la amortiguación del talón ofrecen una comodidad ilimitada.",
        images: [
            "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&q=80",
        ],
        brand: "New Balance",
        category: "Running",
        stock: 14,
        features: [
            "Entresuela ABZORB absorbe los impactos",
            "Suela Stability Web proporciona soporte",
            "Parte superior de malla y ante",
            "Amortiguación N-ergy",
        ],
        sizes: [40, 41, 42, 43],
        colors: ["Grey", "Navy", "Black"],
    },
    {
        id: "11",
        name: "Converse Chuck 70",
        price: 74990,
        description: "El Chuck 70 combina los mejores detalles de los Chuck de los años 70 con una artesanía impecable y materiales premium. Un ícono de estilo elevado.",
        images: [
            "https://images.unsplash.com/photo-1607522370275-f14206abe5d3?w=800&q=80",
        ],
        brand: "Converse",
        category: "Clásico",
        stock: 40,
        features: [
            "Lona premium de 12 oz",
            "Amortiguación OrthoLite",
            "Parche del tobillo vintage",
            "Suela de goma brillante",
        ],
        sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44],
        colors: ["Black", "Parchment", "Red"],
    }
];
